### ISSUE TITLE
Work Share Plan implementation

### ISSUE THREAD

**Issue by cirtur** [evcka/eshc-intranet#50]
We don't yet have full knowledge of what the WSP proposal that passes will be, although we can be pretty confident of some things.

1) There will be a list of roles that people can take. So, we need a way to view all the roles, and to allow people to see more information, maybe indicate an interest in it, and the role be assigned to them.
2) Most people have said they'd like to learn a role from the person who was doing it previously, through shadowing and asking them questions.  It would be easy to record who had the role previously, and that could be displayed, with maybe some contact info to help the new person with the role get in touch.
3) Detailed instructions on how to do the jobs, with videos and stuff, I guess the wiki can function like that partially.

**Comment by evcka** [comment]
basic level done. Roles need adding in admin panel.
